export default [
  {
    id: '1',
    icon: 'question-mark-circle',
    title: 'Lihat Panduan',
    navigation: "GuideList",
    enabled: true,
  },
  {
    id: '2',
    icon: 'document-text',
    title: 'Peng Surat',
    navigation: "GuideList",
    enabled: false,
  },
  {
    id: '3',
    icon: 'chat-bubble-oval-left-elipsis',
    title: 'Layanan Aduan',
    navigation: "GuideList",
    enabled: false,
  },
  {
    id: '4',
    icon: 'wallet',
    title: 'Riwayat Bayar',
    navigation: "GuideList",
    enabled: false,
  },
  {
    id: '5',
    icon: 'identification',
    title: 'Buku Nilai Anak',
    navigation: "GuideList",
    enabled: false,
  },
  {
    id: '6',
    icon: 'puzzle-piece',
    title: 'Aktivitas Anak',
    navigation: "GuideList",
    enabled: false,
  },
  {
    id: '7',
    icon: 'newspaper',
    title: 'Amal Yaumi',
    navigation: "GuideList",
    enabled: false,
  },
  {
    id: '8',
    icon: 'clipboard-document-check',
    title: 'Absensi Anak',
    navigation: "GuideList",
    enabled: false,
  },
] as const;